[2024-11-17T06:47:05.808+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:47:05.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:47:05.811+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:47:05.810+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:47:05.864+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:47:05.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-17T06:47:05.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:47:05.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.078 seconds
[2024-11-17T06:47:36.394+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:47:36.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:47:36.397+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:47:36.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:47:36.410+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:47:36.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-17T06:47:36.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:47:36.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.034 seconds
[2024-11-17T06:48:06.870+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:48:06.871+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:48:06.872+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:48:06.872+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:48:06.895+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:48:06.892+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-17T06:48:06.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:48:06.913+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.047 seconds
[2024-11-17T06:48:37.286+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:48:37.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:48:37.288+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:48:37.288+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:48:37.298+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:48:37.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-17T06:48:37.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:48:37.316+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.034 seconds
[2024-11-17T06:49:07.708+0000] {processor.py:186} INFO - Started process (PID=199) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:49:07.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:49:07.710+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:49:07.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:49:07.719+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:49:07.717+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-17T06:49:07.720+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:49:07.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T06:49:38.209+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:49:38.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:49:38.211+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:49:38.211+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:49:38.220+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:49:38.218+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-17T06:49:38.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:49:38.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.030 seconds
[2024-11-17T06:50:08.955+0000] {processor.py:186} INFO - Started process (PID=209) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:50:08.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:50:08.957+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:50:08.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:50:08.967+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:50:08.965+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-17T06:50:08.968+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:50:08.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T06:50:39.511+0000] {processor.py:186} INFO - Started process (PID=214) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:50:39.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:50:39.513+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:50:39.513+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:50:39.523+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:50:39.521+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-17T06:50:39.524+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:50:39.534+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.027 seconds
[2024-11-17T06:51:09.997+0000] {processor.py:186} INFO - Started process (PID=219) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:51:09.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:51:09.999+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:51:09.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:51:10.008+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:51:10.006+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-17T06:51:10.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:51:10.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.030 seconds
[2024-11-17T06:51:40.139+0000] {processor.py:186} INFO - Started process (PID=224) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:51:40.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:51:40.141+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:51:40.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:51:40.160+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:51:40.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-17T06:51:40.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:51:40.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.043 seconds
[2024-11-17T06:52:10.789+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:52:10.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:52:10.791+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:52:10.791+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:52:10.803+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:52:10.800+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-17T06:52:10.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:52:10.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T06:52:41.205+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:52:41.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:52:41.207+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:52:41.206+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:52:41.217+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:52:41.214+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-17T06:52:41.217+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:52:41.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T06:52:43.243+0000] {processor.py:186} INFO - Started process (PID=239) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:52:43.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:52:43.246+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:52:43.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:52:43.260+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:52:43.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.9/site-packages/airflow/__init__.py)
[2024-11-17T06:52:43.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:52:43.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.036 seconds
[2024-11-17T06:53:14.108+0000] {processor.py:186} INFO - Started process (PID=244) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:53:14.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:53:14.111+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:53:14.110+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:53:14.120+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:53:14.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.9/site-packages/airflow/__init__.py)
[2024-11-17T06:53:14.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:53:14.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T06:53:44.623+0000] {processor.py:186} INFO - Started process (PID=249) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:53:44.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:53:44.625+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:53:44.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:53:44.636+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:53:44.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.9/site-packages/airflow/__init__.py)
[2024-11-17T06:53:44.637+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:53:44.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T06:54:15.163+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:54:15.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:54:15.166+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:54:15.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:54:15.177+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:54:15.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.9/site-packages/airflow/__init__.py)
[2024-11-17T06:54:15.179+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:54:15.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.030 seconds
[2024-11-17T06:54:45.678+0000] {processor.py:186} INFO - Started process (PID=259) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:54:45.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:54:45.681+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:54:45.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:54:45.692+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:54:45.689+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.9/site-packages/airflow/__init__.py)
[2024-11-17T06:54:45.693+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:54:45.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.033 seconds
[2024-11-17T06:55:01.395+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:55:01.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:55:01.397+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:55:01.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:55:01.416+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:55:01.413+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.9/site-packages/airflow/__init__.py)
[2024-11-17T06:55:01.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:55:01.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.040 seconds
[2024-11-17T06:55:32.256+0000] {processor.py:186} INFO - Started process (PID=269) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:55:32.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:55:32.258+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:55:32.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:55:32.268+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:55:32.265+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.9/site-packages/airflow/__init__.py)
[2024-11-17T06:55:32.269+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:55:32.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T06:56:02.805+0000] {processor.py:186} INFO - Started process (PID=274) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:56:02.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:56:02.807+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:56:02.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:56:02.821+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:56:02.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.9/site-packages/airflow/__init__.py)
[2024-11-17T06:56:02.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:56:02.833+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T06:56:33.693+0000] {processor.py:186} INFO - Started process (PID=279) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:56:33.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:56:33.695+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:56:33.695+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:56:33.706+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:56:33.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.9/site-packages/airflow/__init__.py)
[2024-11-17T06:56:33.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:56:33.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T06:57:04.176+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:57:04.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:57:04.179+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:57:04.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:57:04.189+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:57:04.187+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.9/site-packages/airflow/__init__.py)
[2024-11-17T06:57:04.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:57:04.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.035 seconds
[2024-11-17T06:57:05.213+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:57:05.214+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:57:05.215+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:57:05.215+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:57:05.230+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:57:05.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T06:57:05.231+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:57:05.242+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T06:57:35.783+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:57:35.784+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:57:35.785+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:57:35.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:57:35.797+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:57:35.795+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T06:57:35.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:57:35.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.035 seconds
[2024-11-17T06:58:06.293+0000] {processor.py:186} INFO - Started process (PID=299) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:58:06.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:58:06.295+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:58:06.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:58:06.312+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:58:06.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T06:58:06.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:58:06.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.037 seconds
[2024-11-17T06:58:37.205+0000] {processor.py:186} INFO - Started process (PID=304) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:58:37.206+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:58:37.207+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:58:37.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:58:37.219+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:58:37.216+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T06:58:37.220+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:58:37.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.033 seconds
[2024-11-17T06:59:07.715+0000] {processor.py:186} INFO - Started process (PID=309) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:59:07.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:59:07.717+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:59:07.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:59:07.731+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:59:07.729+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T06:59:07.732+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:59:07.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T06:59:38.580+0000] {processor.py:186} INFO - Started process (PID=314) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:59:38.581+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T06:59:38.583+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:59:38.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:59:38.592+0000] {logging_mixin.py:190} INFO - [2024-11-17T06:59:38.590+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T06:59:38.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T06:59:38.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T07:00:09.137+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:00:09.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:00:09.139+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:00:09.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:00:09.149+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:00:09.147+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:00:09.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:00:09.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.026 seconds
[2024-11-17T07:00:40.043+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:00:40.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:00:40.046+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:00:40.046+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:00:40.063+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:00:40.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:00:40.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:00:40.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.038 seconds
[2024-11-17T07:01:10.956+0000] {processor.py:186} INFO - Started process (PID=329) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:01:10.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:01:10.959+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:01:10.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:01:10.977+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:01:10.972+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:01:10.978+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:01:10.989+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.040 seconds
[2024-11-17T07:01:41.861+0000] {processor.py:186} INFO - Started process (PID=334) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:01:41.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:01:41.863+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:01:41.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:01:41.876+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:01:41.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:01:41.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:01:41.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.035 seconds
[2024-11-17T07:02:12.792+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:02:12.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:02:12.794+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:02:12.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:02:12.811+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:02:12.807+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:02:12.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:02:12.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.041 seconds
[2024-11-17T07:02:43.678+0000] {processor.py:186} INFO - Started process (PID=344) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:02:43.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:02:43.680+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:02:43.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:02:43.690+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:02:43.687+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:02:43.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:02:43.705+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.030 seconds
[2024-11-17T07:03:13.765+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:03:13.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:03:13.768+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:03:13.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:03:13.777+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:03:13.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:03:13.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:03:13.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T07:03:44.388+0000] {processor.py:186} INFO - Started process (PID=354) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:03:44.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:03:44.390+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:03:44.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:03:44.404+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:03:44.401+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:03:44.405+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:03:44.421+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.038 seconds
[2024-11-17T07:04:15.361+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:04:15.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:04:15.363+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:04:15.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:04:15.374+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:04:15.372+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:04:15.375+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:04:15.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.033 seconds
[2024-11-17T07:04:23.501+0000] {processor.py:186} INFO - Started process (PID=364) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:04:23.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:04:23.503+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:04:23.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:04:23.518+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:04:23.516+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:04:23.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:04:23.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.038 seconds
[2024-11-17T07:04:54.447+0000] {processor.py:186} INFO - Started process (PID=369) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:04:54.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:04:54.449+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:04:54.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:04:54.461+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:04:54.458+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:04:54.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:04:54.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.035 seconds
[2024-11-17T07:05:25.320+0000] {processor.py:186} INFO - Started process (PID=374) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:05:25.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:05:25.323+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:05:25.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:05:25.343+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:05:25.339+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:05:25.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:05:25.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.039 seconds
[2024-11-17T07:05:56.222+0000] {processor.py:186} INFO - Started process (PID=379) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:05:56.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:05:56.225+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:05:56.224+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:05:56.238+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:05:56.235+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:05:56.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:05:56.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T07:06:26.294+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:06:26.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:06:26.296+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:06:26.296+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:06:26.308+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:06:26.305+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:06:26.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:06:26.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.033 seconds
[2024-11-17T07:06:56.392+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:06:56.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:06:56.394+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:06:56.394+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:06:56.404+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:06:56.402+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:06:56.405+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:06:56.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T07:07:27.384+0000] {processor.py:186} INFO - Started process (PID=394) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:07:27.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:07:27.386+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:07:27.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:07:27.399+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:07:27.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:07:27.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:07:27.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.036 seconds
[2024-11-17T07:07:58.444+0000] {processor.py:186} INFO - Started process (PID=399) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:07:58.444+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:07:58.446+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:07:58.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:07:58.458+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:07:58.456+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:07:58.459+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:07:58.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.030 seconds
[2024-11-17T07:08:29.420+0000] {processor.py:186} INFO - Started process (PID=404) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:08:29.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:08:29.422+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:08:29.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:08:29.434+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:08:29.432+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:08:29.436+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:08:29.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.037 seconds
[2024-11-17T07:09:00.382+0000] {processor.py:186} INFO - Started process (PID=409) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:09:00.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:09:00.384+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:09:00.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:09:00.396+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:09:00.393+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:09:00.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:09:00.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.035 seconds
[2024-11-17T07:09:31.346+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:09:31.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:09:31.348+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:09:31.348+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:09:31.361+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:09:31.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:09:31.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:09:31.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.035 seconds
[2024-11-17T07:10:02.400+0000] {processor.py:186} INFO - Started process (PID=419) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:10:02.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:10:02.402+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:10:02.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:10:02.413+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:10:02.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:10:02.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:10:02.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.027 seconds
[2024-11-17T07:10:33.400+0000] {processor.py:186} INFO - Started process (PID=424) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:10:33.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:10:33.402+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:10:33.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:10:33.425+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:10:33.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:10:33.429+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:10:33.446+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.050 seconds
[2024-11-17T07:11:04.376+0000] {processor.py:186} INFO - Started process (PID=429) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:11:04.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:11:04.379+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:11:04.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:11:04.388+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:11:04.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:11:04.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:11:04.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.030 seconds
[2024-11-17T07:11:35.314+0000] {processor.py:186} INFO - Started process (PID=434) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:11:35.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:11:35.316+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:11:35.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:11:35.330+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:11:35.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:11:35.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:11:35.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.038 seconds
[2024-11-17T07:12:06.319+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:12:06.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:12:06.321+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:12:06.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:12:06.332+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:12:06.330+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:12:06.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:12:06.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.033 seconds
[2024-11-17T07:12:37.323+0000] {processor.py:186} INFO - Started process (PID=444) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:12:37.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:12:37.325+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:12:37.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:12:37.338+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:12:37.335+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:12:37.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:12:37.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T07:13:08.326+0000] {processor.py:186} INFO - Started process (PID=449) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:13:08.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:13:08.328+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:13:08.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:13:08.338+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:13:08.336+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:13:08.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:13:08.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T07:13:39.308+0000] {processor.py:186} INFO - Started process (PID=454) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:13:39.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:13:39.311+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:13:39.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:13:39.323+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:13:39.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:13:39.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:13:39.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.035 seconds
[2024-11-17T07:14:10.334+0000] {processor.py:186} INFO - Started process (PID=459) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:14:10.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:14:10.336+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:14:10.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:14:10.347+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:14:10.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:14:10.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:14:10.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.035 seconds
[2024-11-17T07:14:41.373+0000] {processor.py:186} INFO - Started process (PID=464) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:14:41.374+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:14:41.375+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:14:41.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:14:41.384+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:14:41.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:14:41.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:14:41.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.030 seconds
[2024-11-17T07:16:42.470+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:16:42.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:16:42.472+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:16:42.472+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:16:42.489+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:16:42.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:16:42.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:16:42.501+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.035 seconds
[2024-11-17T07:17:13.458+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:17:13.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:17:13.460+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:17:13.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:17:13.473+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:17:13.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:17:13.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:17:13.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.038 seconds
[2024-11-17T07:17:44.428+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:17:44.429+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:17:44.431+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:17:44.430+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:17:44.448+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:17:44.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:17:44.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:17:44.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.042 seconds
[2024-11-17T07:18:15.474+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:18:15.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:18:15.477+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:18:15.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:18:15.487+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:18:15.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:18:15.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:18:15.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.034 seconds
[2024-11-17T07:19:00.527+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:19:00.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:19:00.529+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:19:00.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:19:00.551+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:19:00.546+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:19:00.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:19:00.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.046 seconds
[2024-11-17T07:19:31.468+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:19:31.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:19:31.470+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:19:31.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:19:31.481+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:19:31.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:19:31.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:19:31.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.034 seconds
[2024-11-17T07:20:02.500+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:20:02.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:20:02.502+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:20:02.502+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:20:02.512+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:20:02.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:20:02.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:20:02.528+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T07:20:32.642+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:20:32.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:20:32.644+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:20:32.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:20:32.661+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:20:32.658+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:20:32.662+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:20:32.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.036 seconds
[2024-11-17T07:21:03.634+0000] {processor.py:186} INFO - Started process (PID=199) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:21:03.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:21:03.636+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:21:03.636+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:21:03.649+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:21:03.647+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:21:03.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:21:03.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T07:21:41.125+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:21:41.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:21:41.127+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:21:41.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:21:41.142+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:21:41.139+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:21:41.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:21:41.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.038 seconds
[2024-11-17T07:22:12.153+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:22:12.154+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:22:12.156+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:22:12.156+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:22:12.180+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:22:12.174+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:22:12.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:22:12.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.054 seconds
[2024-11-17T07:22:43.128+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:22:43.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:22:43.130+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:22:43.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:22:43.139+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:22:43.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:22:43.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:22:43.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T07:23:13.187+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:23:13.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:23:13.189+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:23:13.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:23:13.198+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:23:13.196+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:23:13.199+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:23:13.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.030 seconds
[2024-11-17T07:23:44.222+0000] {processor.py:186} INFO - Started process (PID=199) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:23:44.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:23:44.224+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:23:44.224+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:23:44.241+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:23:44.239+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:23:44.243+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:23:44.258+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.040 seconds
[2024-11-17T07:24:15.039+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:24:15.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:24:15.042+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:24:15.042+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:24:15.052+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:24:15.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:24:15.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:24:15.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T07:24:45.093+0000] {processor.py:186} INFO - Started process (PID=209) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:24:45.094+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:24:45.095+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:24:45.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:24:45.106+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:24:45.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:24:45.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:24:45.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.033 seconds
[2024-11-17T07:25:16.099+0000] {processor.py:186} INFO - Started process (PID=214) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:25:16.099+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:25:16.101+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:25:16.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:25:16.110+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:25:16.108+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:25:16.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:25:16.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T07:25:46.319+0000] {processor.py:186} INFO - Started process (PID=219) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:25:46.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:25:46.321+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:25:46.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:25:46.340+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:25:46.335+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:25:46.342+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:25:46.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.049 seconds
[2024-11-17T07:26:17.292+0000] {processor.py:186} INFO - Started process (PID=224) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:26:17.293+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:26:17.295+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:26:17.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:26:17.305+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:26:17.303+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:26:17.306+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:26:17.316+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.028 seconds
[2024-11-17T07:26:48.297+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:26:48.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:26:48.299+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:26:48.299+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:26:48.311+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:26:48.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:26:48.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:26:48.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.030 seconds
[2024-11-17T07:27:19.343+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:27:19.344+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:27:19.346+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:27:19.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:27:19.362+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:27:19.359+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:27:19.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:27:19.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.035 seconds
[2024-11-17T07:27:31.788+0000] {processor.py:186} INFO - Started process (PID=239) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:27:31.789+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:27:31.791+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:27:31.791+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:27:31.816+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:27:31.812+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:27:31.817+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:27:31.833+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.049 seconds
[2024-11-17T07:28:05.646+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:28:05.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:28:05.648+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:28:05.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:28:05.662+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:28:05.659+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:28:05.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:28:05.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.036 seconds
[2024-11-17T07:28:36.677+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:28:36.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:28:36.679+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:28:36.679+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:28:36.690+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:28:36.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:28:36.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:28:36.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.028 seconds
[2024-11-17T07:29:06.743+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:29:06.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:29:06.745+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:29:06.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:29:06.755+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:29:06.753+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:29:06.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:29:06.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.031 seconds
[2024-11-17T07:29:37.782+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:29:37.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:29:37.785+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:29:37.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:29:37.795+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:29:37.793+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:29:37.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:29:37.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T07:30:07.862+0000] {processor.py:186} INFO - Started process (PID=199) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:30:07.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:30:07.864+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:30:07.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:30:07.874+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:30:07.872+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:30:07.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:30:07.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.030 seconds
[2024-11-17T07:30:38.911+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:30:38.912+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:30:38.913+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:30:38.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:30:38.925+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:30:38.923+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:30:38.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:30:38.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.033 seconds
[2024-11-17T07:31:09.977+0000] {processor.py:186} INFO - Started process (PID=209) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:31:09.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:31:09.979+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:31:09.979+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:31:09.996+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:31:09.992+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:31:09.997+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:31:10.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.044 seconds
[2024-11-17T07:31:41.050+0000] {processor.py:186} INFO - Started process (PID=214) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:31:41.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:31:41.052+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:31:41.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:31:41.072+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:31:41.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:31:41.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:31:41.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.053 seconds
[2024-11-17T07:32:12.102+0000] {processor.py:186} INFO - Started process (PID=219) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:32:12.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:32:12.104+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:32:12.104+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:32:12.117+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:32:12.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:32:12.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:32:12.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.035 seconds
[2024-11-17T07:32:43.070+0000] {processor.py:186} INFO - Started process (PID=224) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:32:43.071+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:32:43.072+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:32:43.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:32:43.084+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:32:43.082+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:32:43.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:32:43.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.034 seconds
[2024-11-17T07:33:14.060+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:14.060+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:33:14.062+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:33:14.062+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:14.080+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:33:14.076+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:33:14.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:14.098+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.042 seconds
[2024-11-17T07:33:19.109+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:19.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:33:19.111+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:33:19.110+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:19.130+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:33:19.127+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from your_dag import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'your_dag'
[2024-11-17T07:33:19.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:19.142+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.038 seconds
[2024-11-17T07:33:39.312+0000] {processor.py:186} INFO - Started process (PID=239) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:39.313+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:33:39.315+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:33:39.314+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:39.336+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:33:39.334+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from your_dag import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'your_dag'
[2024-11-17T07:33:39.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:39.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.042 seconds
[2024-11-17T07:33:39.376+0000] {processor.py:186} INFO - Started process (PID=244) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:39.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:33:39.378+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:33:39.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:39.388+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:33:39.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from your_dag import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'your_dag'
[2024-11-17T07:33:39.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:39.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.027 seconds
[2024-11-17T07:33:39.747+0000] {processor.py:186} INFO - Started process (PID=249) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:39.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:33:39.749+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:33:39.749+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:39.763+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:33:39.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from your_dag import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'your_dag'
[2024-11-17T07:33:39.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:33:39.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T07:34:11.251+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:34:11.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:34:11.253+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:34:11.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:34:11.281+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:34:11.278+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from your_dag import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'your_dag'
[2024-11-17T07:34:11.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:34:11.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.053 seconds
[2024-11-17T07:34:42.280+0000] {processor.py:186} INFO - Started process (PID=259) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:34:42.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:34:42.282+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:34:42.282+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:34:42.295+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:34:42.292+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from your_dag import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'your_dag'
[2024-11-17T07:34:42.296+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:34:42.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.034 seconds
[2024-11-17T07:35:13.350+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:35:13.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:35:13.352+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:35:13.352+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:35:13.362+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:35:13.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from your_dag import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'your_dag'
[2024-11-17T07:35:13.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:35:13.378+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T07:35:43.502+0000] {processor.py:186} INFO - Started process (PID=269) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:35:43.503+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:35:43.504+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:35:43.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:35:43.516+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:35:43.514+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from your_dag import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'your_dag'
[2024-11-17T07:35:43.517+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:35:43.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.034 seconds
[2024-11-17T07:36:00.685+0000] {processor.py:186} INFO - Started process (PID=274) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:36:00.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:36:00.688+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:36:00.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:36:00.703+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:36:00.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:36:00.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:36:00.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.037 seconds
[2024-11-17T07:36:30.793+0000] {processor.py:186} INFO - Started process (PID=279) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:36:30.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:36:30.795+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:36:30.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:36:30.809+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:36:30.807+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:36:30.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:36:30.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.039 seconds
[2024-11-17T07:37:01.064+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:37:01.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:37:01.069+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:37:01.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:37:01.101+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:37:01.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:37:01.104+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:37:01.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.066 seconds
[2024-11-17T07:37:31.269+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:37:31.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:37:31.271+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:37:31.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:37:31.289+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:37:31.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:37:31.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:37:31.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.045 seconds
[2024-11-17T07:38:01.413+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:38:01.413+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:38:01.415+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:38:01.415+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:38:01.425+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:38:01.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:38:01.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:38:01.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.033 seconds
[2024-11-17T07:38:31.552+0000] {processor.py:186} INFO - Started process (PID=299) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:38:31.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:38:31.554+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:38:31.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:38:31.564+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:38:31.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:38:31.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:38:31.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.034 seconds
[2024-11-17T07:39:01.643+0000] {processor.py:186} INFO - Started process (PID=304) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:39:01.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:39:01.646+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:39:01.645+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:39:01.656+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:39:01.654+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:39:01.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:39:01.666+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.026 seconds
[2024-11-17T07:39:31.740+0000] {processor.py:186} INFO - Started process (PID=309) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:39:31.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:39:31.742+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:39:31.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:39:31.752+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:39:31.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:39:31.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:39:31.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T07:40:01.930+0000] {processor.py:186} INFO - Started process (PID=314) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:40:01.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:40:01.933+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:40:01.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:40:01.944+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:40:01.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:40:01.945+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:40:01.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T07:40:32.048+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:40:32.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:40:32.050+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:40:32.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:40:32.062+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:40:32.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:40:32.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:40:32.077+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.033 seconds
[2024-11-17T07:41:02.219+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:41:02.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:41:02.223+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:41:02.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:41:02.233+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:41:02.231+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:41:02.234+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:41:02.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.034 seconds
[2024-11-17T07:41:32.339+0000] {processor.py:186} INFO - Started process (PID=329) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:41:32.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:41:32.341+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:41:32.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:41:32.351+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:41:32.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:41:32.352+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:41:32.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T07:42:02.431+0000] {processor.py:186} INFO - Started process (PID=334) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:42:02.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:42:02.433+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:42:02.433+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:42:02.448+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:42:02.445+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:42:02.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:42:02.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.037 seconds
[2024-11-17T07:42:32.528+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:42:32.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:42:32.530+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:42:32.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:42:32.543+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:42:32.541+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:42:32.544+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:42:32.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.030 seconds
[2024-11-17T07:42:46.706+0000] {processor.py:186} INFO - Started process (PID=344) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:42:46.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:42:46.709+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:42:46.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:42:46.753+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:42:46.747+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:42:46.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:42:46.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.076 seconds
[2024-11-17T07:43:16.910+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:43:16.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:43:16.912+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:43:16.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:43:16.922+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:43:16.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:43:16.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:43:16.938+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.032 seconds
[2024-11-17T07:43:46.975+0000] {processor.py:186} INFO - Started process (PID=354) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:43:46.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:43:46.977+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:43:46.976+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:43:46.989+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:43:46.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:43:46.990+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:43:47.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.036 seconds
[2024-11-17T07:44:17.108+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:44:17.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/your_dag.py for tasks to queue
[2024-11-17T07:44:17.111+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:44:17.110+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:44:17.124+0000] {logging_mixin.py:190} INFO - [2024-11-17T07:44:17.121+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/your_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/your_dag.py", line 3, in <module>
    from plugins.sql_queries import QUERIES  # Importation des requêtes
ModuleNotFoundError: No module named 'plugins'
[2024-11-17T07:44:17.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/your_dag.py
[2024-11-17T07:44:17.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/your_dag.py took 0.037 seconds
